export const POST_USER_DATA_REQUEST = "POST_USER_DATA_REQUEST"
export const POST_USER_DATA_FAILURE = "POST_USER_DATA_FAILURE"
export const POST_USER_DATA_SUCCESS = "POST_USER_DATA_SUCCESS"


export const GET_USER_DATA_REQUEST = "GET_USER_DATA_REQUEST"
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS"
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_SUCCESS"


export const EDIT_USER_DATA_REQUEST = "EDIT_USER_DATA_REQUEST"
export const EDIT_USER_DATA_SUCCESS = "EDIT_USER_DATA_SUCCESS"
export const EDIT_USER_DATA_FAILURE = "EDIT_USER_DATA_FAILURE"